# Generated by Django 4.2.6 on 2023-10-15 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BcCompany',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BcPeople',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('attachable_sgid', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('personable_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('admin', models.BooleanField()),
                ('owner', models.BooleanField()),
                ('client', models.BooleanField()),
                ('employee', models.BooleanField()),
                ('time_zone', models.CharField(max_length=30)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('can_manage_projects', models.BooleanField()),
                ('can_manage_people', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bccompany')),
            ],
        ),
    ]
