# Generated by Django 4.2.6 on 2023-10-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcProjectTool',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField()),
                ('position', models.IntegerField(null=True)),
                ('url', models.URLField()),
                ('app_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BcProject',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(max_length=30)),
                ('clients_enabled', models.BooleanField()),
                ('bookmark_url', models.URLField()),
                ('url', models.URLField()),
                ('app_url', models.URLField()),
                ('dock', models.ManyToManyField(to='bc.bcprojecttool')),
            ],
        ),
    ]
