# Generated by Django 4.2.6 on 2023-11-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bc', '0002_bcprojecttool_bcproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcTodoset',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('visible_to_clients', models.BooleanField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('inherits_status', models.BooleanField()),
                ('type', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('app_url', models.URLField()),
                ('bookmark_url', models.URLField()),
                ('position', models.IntegerField(null=True)),
                ('completed', models.BooleanField()),
                ('completed_ratio', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('todolists_count', models.IntegerField()),
                ('todolists_url', models.URLField()),
                ('app_todoslists_url', models.URLField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcproject')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcpeople')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BcTodolist',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('visible_to_clients', models.BooleanField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('inherits_status', models.BooleanField()),
                ('type', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('app_url', models.URLField()),
                ('bookmark_url', models.URLField()),
                ('position', models.IntegerField(null=True)),
                ('completed', models.BooleanField()),
                ('completed_ratio', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('subscription_url', models.URLField()),
                ('comments_count', models.IntegerField()),
                ('comments_url', models.URLField()),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('todos_url', models.URLField()),
                ('app_todos_url', models.URLField()),
                ('groups_url', models.URLField(blank=True, null=True)),
                ('group_position_url', models.URLField(blank=True, null=True)),
                ('is_todolist_group', models.BooleanField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcproject')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcpeople')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
