# Generated by Django 4.2.6 on 2023-11-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bc', '0003_bctodoset_bctodolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcTodoCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcpeople')),
            ],
        ),
        migrations.CreateModel(
            name='BcTodo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('visible_to_clients', models.BooleanField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('inherits_status', models.BooleanField()),
                ('type', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('app_url', models.URLField()),
                ('bookmark_url', models.URLField()),
                ('position', models.IntegerField(null=True)),
                ('completed', models.BooleanField()),
                ('subscription_url', models.URLField()),
                ('comments_count', models.IntegerField()),
                ('comments_url', models.URLField()),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('starts_on', models.DateField(null=True)),
                ('due_on', models.DateField(null=True)),
                ('completion_url', models.URLField()),
                ('assignees', models.ManyToManyField(blank=True, related_name='todo_assignees', to='bc.bcpeople')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcproject')),
                ('completion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bc.bctodocompletion')),
                ('completion_subscribers', models.ManyToManyField(blank=True, related_name='todo_completion_subscribers', to='bc.bcpeople')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcpeople')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
