# Generated by Django 4.2.6 on 2023-11-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bc', '0005_bcmessagecategory_bcmessageboard_bcmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcQuestionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=30)),
                ('days', models.JSONField(blank=True, null=True)),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('week_instance', models.IntegerField(blank=True, null=True)),
                ('week_interval', models.IntegerField(blank=True, null=True)),
                ('month_interval', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('duration', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BcQuestionnaire',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('visible_to_clients', models.BooleanField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('inherits_status', models.BooleanField()),
                ('type', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('app_url', models.URLField()),
                ('bookmark_url', models.URLField()),
                ('position', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('questions_count', models.IntegerField()),
                ('questions_url', models.URLField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcproject')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcpeople')),
            ],
        ),
        migrations.CreateModel(
            name='BcQuestionAnswer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('visible_to_clients', models.BooleanField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('inherits_status', models.BooleanField()),
                ('type', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('app_url', models.URLField()),
                ('bookmark_url', models.URLField()),
                ('subscription_url', models.URLField()),
                ('comments_count', models.IntegerField()),
                ('comments_url', models.URLField()),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('group_on', models.DateField(null=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcproject')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcpeople')),
            ],
        ),
        migrations.CreateModel(
            name='BcQuestion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('visible_to_clients', models.BooleanField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('inherits_status', models.BooleanField()),
                ('type', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('app_url', models.URLField()),
                ('bookmark_url', models.URLField()),
                ('subscription_url', models.URLField()),
                ('object_id', models.PositiveIntegerField()),
                ('paused', models.BooleanField()),
                ('answers_count', models.IntegerField()),
                ('answers_url', models.URLField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcproject')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcpeople')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcquestionschedule')),
            ],
        ),
    ]
