# Generated by Django 4.2.6 on 2023-11-27 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bc', '0007_bcscheduleentry_bcschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcComment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('visible_to_clients', models.BooleanField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('inherits_status', models.BooleanField()),
                ('type', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('app_url', models.URLField()),
                ('bookmark_url', models.URLField()),
                ('parent_object_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcproject')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcpeople')),
                ('parent_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
