# Generated by Django 4.2.6 on 2023-11-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bc', '0008_bccomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcVault',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('visible_to_clients', models.BooleanField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('inherits_status', models.BooleanField()),
                ('type', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('app_url', models.URLField()),
                ('bookmark_url', models.URLField()),
                ('position', models.IntegerField(null=True)),
                ('parent_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('documents_count', models.IntegerField()),
                ('documents_url', models.URLField()),
                ('uploads_count', models.IntegerField()),
                ('uploads_url', models.URLField()),
                ('vaults_count', models.IntegerField()),
                ('vaults_url', models.URLField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcproject')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcpeople')),
                ('parent_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='BcUpload',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('visible_to_clients', models.BooleanField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('inherits_status', models.BooleanField()),
                ('type', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('app_url', models.URLField()),
                ('bookmark_url', models.URLField()),
                ('subscription_url', models.URLField()),
                ('comments_count', models.IntegerField()),
                ('comments_url', models.URLField()),
                ('position', models.IntegerField(null=True)),
                ('parent_object_id', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.CharField(max_length=30)),
                ('byte_size', models.BigIntegerField()),
                ('filename', models.CharField(max_length=30)),
                ('download_url', models.URLField()),
                ('app_download_url', models.URLField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcproject')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcpeople')),
                ('parent_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='BcDocument',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('visible_to_clients', models.BooleanField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('inherits_status', models.BooleanField()),
                ('type', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('app_url', models.URLField()),
                ('bookmark_url', models.URLField()),
                ('subscription_url', models.URLField()),
                ('comments_count', models.IntegerField()),
                ('comments_url', models.URLField()),
                ('position', models.IntegerField(null=True)),
                ('parent_object_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcproject')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc.bcpeople')),
                ('parent_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
